name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master
trigger:
  - "*"

variables:
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-jolly-field-0ab036d03-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    name: DeployStaticWebApp
    displayName: Deploy Static Web App
    condition: and(succeeded(), eq(variables.isMaster, 'true'))
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0AB036D03)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "api" # Api source code path - optional
      output_location: "build" # Built app content directory - optional
###### End of Repository/Build Configurations ######
    env:
      REACT_APP_AES_SECRET: $(AES_SECRET)
  
  - task: AzureStaticWebApp@0
    name: DeployStaticWebAppPreviewEnv
    displayName: Deploy Static Web App
    condition: and(succeeded(), ne(variables.isMaster, 'true'))
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0AB036D03)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "api" # Api source code path - optional
      output_location: "build" # Built app content directory - optional
###### End of Repository/Build Configurations ######
      deployment_environment: "release"
    env:
      REACT_APP_AES_SECRET: $(AES_SECRET)
